folder: "./real_data/BPRP/"
phase_object: false
elliptical_pupil: false
pre_process: false
equalization: false   # does not work well, appears patchy
wfe_correction: false
wfe_alpha: 0.1
data_format: "npz"
keyword: "BPRP"
index_to_exclude: ~
roi_size_px: 1660
init_option: "plane"
file_name: "gt_abe.npy"
ROI_length: 332
ROI_center:
  - 664
  - 664
patch_num: 6
recon_alg: "GN"
abe_correction: true
iters: 100
swap_dim: false
