folder: "./real_data/BPRA/"
phase_object: false
elliptical_pupil: false
pupil_edge_soften: 0
pre_process: false
equalization: false
wfe_correction: false
wfe_alpha: 0.1
data_format: "npz"
keyword: "BPRP"
index_to_exclude:
  - 
roi_size_px: 1992
use_ROI: true
ROI_length: 256
ROI_center:
  - 128                              
  - 350
init_option: "plane"                  
file_name: "./real_data/lines/gt_abe.npy"
recon_alg: "GN"           
abe_correction: true
iters: 100
swap_dim: false